name: Run JMeter Tests with Test Data and Plugins

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
  workflow_dispatch: # Allow manual trigger of this workflow

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install JMeter
      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk wget
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 ~/jmeter

      # Step 3: Run JMeter test plan with test data (CSV) and a plugin
      - name: Run JMeter test plan
        run: |
          mkdir -p results
          # Copy test data file to JMeter working directory
          cp test-data/personal-info.csv ~/jmeter/bin/
          # Ensure file is readable
          chmod 644 ~/jmeter/bin/personal-info.csv
          # Convert to Unix-style line endings (just in case)
          dos2unix ~/jmeter/bin/personal-info.csv
          # Copy the plugin to JMeter plugins directory
          cp lib/jmeter-plugins-dummy-0.4.jar ~/jmeter/lib/ext/
          # Verify file placement (debugging step)
          pwd
          ls -l ~/jmeter/bin/
          # Run the JMeter test plan with debugging enabled
          ~/jmeter/bin/jmeter -Juser.dir=~/jmeter/bin -n -t test-plans/test-plan-example-data-driven-test.jmx -l results/results-ddt.jtl -j results/jmeter-ddt.log -Jlog_level.jmeter.services.FileServer=DEBUG
      

        # Step 4: Save results as artifacts
      - name: Upload results folder as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-and-test-results
          path: |
            results/
            test-results/